Repository jenkinsci/plugin-compat-tester, pull requests merged in 2019-09, with the labels that each got.

#186 Update jcommander to a version which supports Java 8 (release redeploy?)
  plugins-compat-tester-cli/pom.xml
Labels: bugfix

#185 Update hooks to make more plugins works properly with PCT
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/PomData.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/BlueOceanHook.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/MultiParentCompileHook.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/PipelineRestApiHook.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/TransformPom.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/model/PluginRemoting.java
  plugins-compat-tester/src/main/resources/nonstandardtagplugins.properties
  plugins-compat-tester/src/test/java/org/jenkins/tools/test/NonStandardTagHookTest.java
  plugins-compat-tester/src/test/java/org/jenkins/tools/test/ScmConnectionSpecialCasesTest.java
  plugins-compat-tester/src/test/resources/nonstandardtagplugins.properties
Labels: enhancement

#189 Code cleanup
  plugins-compat-tester-cli/src/main/java/org/jenkins/tools/test/PluginCompatTesterCli.java
  plugins-compat-tester-gae-client/src/main/java/org/jenkins/tools/test/DataImporter.java
  plugins-compat-tester-gae/src/main/java/org/jenkins/tools/test/dao/DAOUtils.java
  plugins-compat-tester-gae/src/main/java/org/jenkins/tools/test/dao/LogsDAO.java
  plugins-compat-tester-gae/src/main/java/org/jenkins/tools/test/dao/Mappings.java
  plugins-compat-tester-gae/src/main/java/org/jenkins/tools/test/dao/PluginCompatResultDAO.java
  plugins-compat-tester-gae/src/main/java/org/jenkins/tools/test/dao/SecurityTokenDAO.java
  plugins-compat-tester-gae/src/main/java/org/jenkins/tools/test/servlets/DataProviderServlet.java
  plugins-compat-tester-gae/src/main/java/org/jenkins/tools/test/servlets/InitTokenServlet.java
  plugins-compat-tester-gae/src/main/java/org/jenkins/tools/test/servlets/PurgeResultsServlet.java
  plugins-compat-tester-gae/src/main/java/org/jenkins/tools/test/servlets/RetrieveBuildLogServlet.java
  plugins-compat-tester-gae/src/main/java/org/jenkins/tools/test/servlets/RetrieveResultsServlet.java
  plugins-compat-tester-gae/src/main/java/org/jenkins/tools/test/servlets/WritePCTResultServlet.java
  plugins-compat-tester-gae/src/main/java/org/jenkins/tools/test/servlets/util/JsonUtil.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/MavenCoordinates.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/PluginCompatReport.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/PluginCompatResult.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/PluginCompatTesterConfig.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/PluginInfos.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/PomData.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/TestStatus.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/comparators/MavenCoordinatesComparator.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/comparators/VersionComparator.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHook.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHookBeforeCheckout.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHookBeforeExecution.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHooks.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/utils/IOUtils.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/SCMManagerFactory.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/exception/PomExecutionException.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/AbstractMultiParentHook.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/BlueOceanHook.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/DeclarativePipelineHook.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/ExampleMultiParent.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/MultiParentCompileHook.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/NonStandardTagHook.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/PipelineRestApiHook.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/SkipUIHelperPlugins.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/StructsHook.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/SwarmHook.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/TransformPom.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/logging/SystemIOLoggerFilter.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/maven/ExternalMavenRunner.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/maven/InternalMavenRunner.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/maven/MavenRunner.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/model/PluginRemoting.java
  plugins-compat-tester/src/test/java/org/jenkins/tools/test/NonStandardTagHookTest.java
  plugins-compat-tester/src/test/java/org/jenkins/tools/test/PluginCompatTesterTest.java
  plugins-compat-tester/src/test/java/org/jenkins/tools/test/ScmConnectionSpecialCasesTest.java
  plugins-compat-tester/src/test/java/org/jenkins/tools/test/VersionComparatorTest.java
  src/main/docker/installWARSnapshots.groovy
  src/main/docker/readJenkinsVersion.groovy
Labels: internal

#181 [JENKINS-58716] Support checking out plugins with Incremental versions
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/PomData.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/AbstractMultiParentHook.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/model/PluginRemoting.java
  plugins-compat-tester/src/test/java/org/jenkins/tools/test/NonStandardTagHookTest.java
  plugins-compat-tester/src/test/java/org/jenkins/tools/test/ScmConnectionSpecialCasesTest.java
Labels: enhancement

#193 [JENKINS-58114] - Remove the unused Google App Engine mode from PCT
  Dockerfile
  plugins-compat-tester-cli/src/main/java/org/jenkins/tools/test/CliOptions.java
  plugins-compat-tester-cli/src/main/java/org/jenkins/tools/test/PluginCompatTesterCli.java
  plugins-compat-tester-gae-client/pom.xml
  plugins-compat-tester-gae-client/src/main/java/org/jenkins/tools/test/DataImporter.java
  plugins-compat-tester-gae/pom.xml
  plugins-compat-tester-gae/src/main/java/org/jenkins/tools/test/dao/DAOUtils.java
  plugins-compat-tester-gae/src/main/java/org/jenkins/tools/test/dao/LogsDAO.java
  plugins-compat-tester-gae/src/main/java/org/jenkins/tools/test/dao/Mappings.java
  plugins-compat-tester-gae/src/main/java/org/jenkins/tools/test/dao/PluginCompatResultDAO.java
  plugins-compat-tester-gae/src/main/java/org/jenkins/tools/test/dao/SecurityTokenDAO.java
  plugins-compat-tester-gae/src/main/java/org/jenkins/tools/test/servlets/DataProviderServlet.java
  plugins-compat-tester-gae/src/main/java/org/jenkins/tools/test/servlets/HelloWorldServlet.java
  plugins-compat-tester-gae/src/main/java/org/jenkins/tools/test/servlets/InitTokenServlet.java
  plugins-compat-tester-gae/src/main/java/org/jenkins/tools/test/servlets/PurgeResultsServlet.java
  plugins-compat-tester-gae/src/main/java/org/jenkins/tools/test/servlets/RetrieveBuildLogServlet.java
  plugins-compat-tester-gae/src/main/java/org/jenkins/tools/test/servlets/RetrieveResultsServlet.java
  plugins-compat-tester-gae/src/main/java/org/jenkins/tools/test/servlets/SecuritySupport.java
  plugins-compat-tester-gae/src/main/java/org/jenkins/tools/test/servlets/WritePCTResultServlet.java
  plugins-compat-tester-gae/src/main/java/org/jenkins/tools/test/servlets/util/JsonUtil.java
  plugins-compat-tester-gae/src/main/webapp/WEB-INF/appengine-web.xml
  plugins-compat-tester-gae/src/main/webapp/WEB-INF/datastore-indexes.xml
  plugins-compat-tester-gae/src/main/webapp/WEB-INF/jsps/hello.jsp
  plugins-compat-tester-gae/src/main/webapp/WEB-INF/web.xml
  plugins-compat-tester-gae/src/main/webapp/css/chosen/chosen-0.9.5.css
  plugins-compat-tester-gae/src/main/webapp/css/chosen/chosen-sprite.png
  plugins-compat-tester-gae/src/main/webapp/css/jquery-ui/images/ui-bg_flat_55_999999_40x100.png
  plugins-compat-tester-gae/src/main/webapp/css/jquery-ui/images/ui-bg_flat_75_aaaaaa_40x100.png
  plugins-compat-tester-gae/src/main/webapp/css/jquery-ui/images/ui-bg_glass_45_0078ae_1x400.png
  plugins-compat-tester-gae/src/main/webapp/css/jquery-ui/images/ui-bg_glass_55_f8da4e_1x400.png
  plugins-compat-tester-gae/src/main/webapp/css/jquery-ui/images/ui-bg_glass_75_79c9ec_1x400.png
  plugins-compat-tester-gae/src/main/webapp/css/jquery-ui/images/ui-bg_gloss-wave_45_e14f1c_500x100.png
  plugins-compat-tester-gae/src/main/webapp/css/jquery-ui/images/ui-bg_gloss-wave_50_6eac2c_500x100.png
  plugins-compat-tester-gae/src/main/webapp/css/jquery-ui/images/ui-bg_gloss-wave_75_2191c0_500x100.png
  plugins-compat-tester-gae/src/main/webapp/css/jquery-ui/images/ui-bg_inset-hard_100_fcfdfd_1x100.png
  plugins-compat-tester-gae/src/main/webapp/css/jquery-ui/images/ui-icons_0078ae_256x240.png
  plugins-compat-tester-gae/src/main/webapp/css/jquery-ui/images/ui-icons_056b93_256x240.png
  plugins-compat-tester-gae/src/main/webapp/css/jquery-ui/images/ui-icons_d8e7f3_256x240.png
  plugins-compat-tester-gae/src/main/webapp/css/jquery-ui/images/ui-icons_e0fdff_256x240.png
  plugins-compat-tester-gae/src/main/webapp/css/jquery-ui/images/ui-icons_f5e175_256x240.png
  plugins-compat-tester-gae/src/main/webapp/css/jquery-ui/images/ui-icons_f7a50d_256x240.png
  plugins-compat-tester-gae/src/main/webapp/css/jquery-ui/images/ui-icons_fcd113_256x240.png
  plugins-compat-tester-gae/src/main/webapp/css/jquery-ui/jquery-ui-1.8.16.custom.css
  plugins-compat-tester-gae/src/main/webapp/img/pct/spacer.gif
  plugins-compat-tester-gae/src/main/webapp/img/pct/spinner.gif
  plugins-compat-tester-gae/src/main/webapp/index.html
  plugins-compat-tester-gae/src/main/webapp/js/chosen/chosen.jquery-0.9.5.js
  plugins-compat-tester-gae/src/main/webapp/js/chosen/chosen.jquery-0.9.5.min.js
  plugins-compat-tester-gae/src/main/webapp/js/jquery-ui/jquery-ui-1.8.16.custom.min.js
  plugins-compat-tester-gae/src/main/webapp/js/json/json2.js
  plugins-compat-tester-gae/src/main/webapp/js/utils/ajax-utils.js
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/PluginCompatTesterConfig.java
  plugins-compat-tester/pom.xml
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  pom.xml
Labels: removal

#192 Plugin compatibility tester is re-adding test-scoped dependencies rather than merely updating them
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/model/MavenPom.java
Labels: bugfix
