Repository jenkinsci/plugin-compat-tester, pull requests merged in 2019-06, with the labels that each got.

#155 Makefile: Add support of running Makefile on Windows + use 2.164.3 + support custom WARs
  Makefile
  README.md
Labels: internal

#163 Add Release Drafter to the repository
  .github/release-drafter.yml
Labels: internal

#165 Add a release name to the template
  .github/release-drafter.yml
Labels: skip-changelog

#164 Remove obsolete TODO comments from the README, they do not reflect the plans
  README.md
Labels: documentation

#170 [JENKINS-57935] - Check results of the integration tests in #169
  Jenkinsfile
Labels: test
