Repository jenkinsci/plugin-compat-tester, pull requests merged in 2019-10, with the labels that each got.

#198 Do not force maven.test.redirectTestOutputToFile=false on test runs
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/PluginCompatTester.java
Labels: enhancement

#199 Remove the obsolete JENKINS-25625 workaround
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/model/MavenPom.java
Labels: removed

#201 Update parent POM from 1.50 to 1.52
  plugins-compat-tester-model/pom.xml
  pom.xml
Labels: dependencies

#200 More code cleanup
  plugins-compat-tester-cli/src/main/java/org/jenkins/tools/test/CliOptions.java
  plugins-compat-tester-cli/src/main/java/org/jenkins/tools/test/PluginCompatTesterCli.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/MavenCoordinates.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/PluginCompatReport.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/PluginCompatResult.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/PluginCompatTesterConfig.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/PluginInfos.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/PomData.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/TestStatus.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/comparators/MavenCoordinatesComparator.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/comparators/VersionComparator.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHook.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHookBeforeCheckout.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHookBeforeCompile.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHookBeforeExecution.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHooks.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/utils/IOUtils.java
  plugins-compat-tester-model/src/test/java/org/jenkins/tools/test/model/utils/IOUtilsTest.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/SCMManagerFactory.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/exception/PluginSourcesUnavailableException.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/exception/PomExecutionException.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/exception/PomTransformationException.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/AbstractMultiParentHook.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/BlueOceanHook.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/ConfigurationAsCodeHook.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/DeclarativePipelineHook.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/ExampleMultiParent.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/MultiParentCompileHook.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/NonStandardTagHook.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/PipelineRestApiHook.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/SkipUIHelperPlugins.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/StructsHook.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/TransformPom.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/logging/SystemIOLoggerFilter.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/model/MavenPom.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/model/PluginRemoting.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/model/TestExecutionResult.java
  plugins-compat-tester/src/main/resources/resultToReport.xsl
  plugins-compat-tester/src/test/java/org/jenkins/tools/test/NonStandardTagHookTest.java
  plugins-compat-tester/src/test/java/org/jenkins/tools/test/PluginCompatTesterTest.java
  plugins-compat-tester/src/test/java/org/jenkins/tools/test/ScmConnectionSpecialCasesTest.java
  plugins-compat-tester/src/test/java/org/jenkins/tools/test/VersionComparatorTest.java
Labels: internal
