Repository jenkinsci/plugin-compat-tester, pull requests merged in 2019-12, with the labels that each got.

#209 Update Jenkinsfile to use the `infra.runMaven()` step with Azure mirror settings and other performance tweaks
  Jenkinsfile
Labels: internal

#208 Remove references to Jenkins Wiki, move the remaining info
  README.md
Labels: documentation

#213 Update Update Center URL to always use HTTPS
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/PluginCompatTesterConfig.java
Labels: bugfix

#211 Add CODEOWNERS to automate review requests
  .github/CODEOWNERS
Labels: internal

#203 Fix SpotBugs issues + Fix the default Java versioncapturing in PluginCompatTesterConfig#getTestJavaVersion() when other options are disabled
  plugins-compat-tester-cli/src/main/java/org/jenkins/tools/test/PluginCompatTesterCli.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/PluginCompatReport.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/PluginCompatTesterConfig.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/comparators/MavenCoordinatesComparator.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/comparators/VersionComparator.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/MultiParentCompileHook.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/logging/SystemIOLoggerFilter.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/maven/ExternalMavenRunner.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/model/MavenPom.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/model/PluginRemoting.java
  pom.xml
Labels: bugfix, hacktoberfest

#207 Include Docker client executable in the PCT Docker image
  Dockerfile
Labels: enhancement

#194 [JENKINS-58113] - Remove the Internal Maven Mode from PCT + Use maven from PATH when "-mvn" is not specified
  plugins-compat-tester-cli/pom.xml
  plugins-compat-tester-cli/src/main/java/org/jenkins/tools/test/CliOptions.java
  plugins-compat-tester-model/pom.xml
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/PluginCompatTesterConfig.java
  plugins-compat-tester/pom.xml
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/MultiParentCompileHook.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/maven/ExternalMavenRunner.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/maven/InternalMavenRunner.java
  plugins-compat-tester/src/test/java/org/jenkins/tools/test/PluginCompatTesterTest.java
  pom.xml
Labels: enhancement, removed

#214 [JENKINS-60583] - Disable the unstable JCasC integration Test
  Jenkinsfile
Labels: internal
