Repository jenkinsci/plugin-compat-tester, pull requests merged in 2022-07, with the labels that each got.

#372 Support for excluding hooks
  plugins-compat-tester-cli/src/main/java/org/jenkins/tools/test/CliOptions.java
  plugins-compat-tester-cli/src/main/java/org/jenkins/tools/test/PluginCompatTesterCli.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/PluginCompatTesterConfig.java
  plugins-compat-tester-model/src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHooks.java
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  plugins-compat-tester/src/test/java/org/jenkins/tools/test/PluginCompatTesterTest.java
Labels: enhancement

#352 Support running with Java 17
  plugins-compat-tester-cli/pom.xml
Labels: bug

#368 chore: use jenkins infra maven cd reusable workflow
  .github/workflows/cd.yaml
Labels: chore

#363 chore(Jenkinsfile) switch WAR download to https://get.jenkins.io
  Jenkinsfile
Labels: internal, enhancement

#375 Teach PCT about Mina SSHD API plugins
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/MinaSshdApi.java
Labels: enhancement

#348 If we are catching `PomExecutionException` do not claim `SUCCESS`
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/PluginCompatTester.java
Labels: bug
