Repository jenkinsci/plugin-compat-tester, pull requests merged in 2022-01, with the labels that each got.

#337 Fix issue on checkout due to GH changes
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/PluginCompatTester.java
Labels: bugfix

#342 Remove broken powermock test (fix mainline)
  plugins-compat-tester/src/test/java/org/jenkins/tools/test/NonStandardTagHookTest.java
Labels: test

#339 Support on transforming the pom to add/update pluginManagement and properties sections
  plugins-compat-tester/src/main/java/org/jenkins/tools/test/model/MavenPom.java
Labels: enhancement
