Repository jenkinsci/plugin-compat-tester, pull requests merged in 2023-02, with the labels that each got.

#433 Simplify retrieval of `pom.xml` contents
  src/main/java/org/jenkins/tools/test/model/PluginRemoting.java
Labels: internal

#424 Remove `warningMessages`
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/exception/PomExecutionException.java
  src/main/java/org/jenkins/tools/test/hook/SkipUIHelperPlugins.java
  src/main/java/org/jenkins/tools/test/maven/ExternalMavenRunner.java
  src/main/java/org/jenkins/tools/test/model/MavenCoordinates.java
  src/main/java/org/jenkins/tools/test/model/PluginCompatResult.java
  src/main/java/org/jenkins/tools/test/model/PluginRemoting.java
  src/main/java/org/jenkins/tools/test/model/PomData.java
  src/main/java/org/jenkins/tools/test/model/TestExecutionResult.java
  src/main/resources/org/jenkins/tools/test/resultToReport.xsl
Labels: removed

#423 Remove cache options
  Makefile
  README.md
  src/main/docker/run-pct.sh
  src/main/java/org/jenkins/tools/test/CliOptions.java
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/PluginCompatTesterCli.java
  src/main/java/org/jenkins/tools/test/model/PluginCompatReport.java
  src/main/java/org/jenkins/tools/test/model/PluginCompatTesterConfig.java
  src/test/java/org/jenkins/tools/test/PluginCompatTesterTest.java
Labels: removed

#425 Remove unnecessary class loaders
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHooks.java
Labels: removed

#419 Delete plugin selection modes other than `-war`
  Jenkinsfile
  README.md
  src/main/java/org/jenkins/tools/test/CliOptions.java
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/PluginCompatTesterCli.java
  src/main/java/org/jenkins/tools/test/hook/DeclarativePipelineMigrationHook.java
  src/main/java/org/jenkins/tools/test/hook/MinaSshdApi.java
  src/main/java/org/jenkins/tools/test/hook/PipelineStageViewHook.java
  src/main/java/org/jenkins/tools/test/model/MavenBom.java
  src/main/java/org/jenkins/tools/test/model/PCTPlugin.java
  src/main/java/org/jenkins/tools/test/model/PluginCompatResult.java
  src/main/java/org/jenkins/tools/test/model/PluginCompatTesterConfig.java
  src/main/java/org/jenkins/tools/test/model/PomData.java
  src/main/java/org/jenkins/tools/test/model/TestExecutionResult.java
  src/test/java/org/jenkins/tools/test/PluginCompatTesterTest.java
Labels: removed

#422 Clean up imports and whitespace
  pom.xml
  src/main/java/org/jenkins/tools/test/CliOptions.java
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/PluginCompatTesterCli.java
  src/main/java/org/jenkins/tools/test/exception/ExecutedTestNamesSolverException.java
  src/main/java/org/jenkins/tools/test/exception/PluginSourcesUnavailableException.java
  src/main/java/org/jenkins/tools/test/exception/PomExecutionException.java
  src/main/java/org/jenkins/tools/test/exception/PomTransformationException.java
  src/main/java/org/jenkins/tools/test/hook/AbstractMultiParentHook.java
  src/main/java/org/jenkins/tools/test/hook/BlueOceanHook.java
  src/main/java/org/jenkins/tools/test/hook/ConfigurationAsCodeHook.java
  src/main/java/org/jenkins/tools/test/hook/DeclarativePipelineHook.java
  src/main/java/org/jenkins/tools/test/hook/DeclarativePipelineMigrationHook.java
  src/main/java/org/jenkins/tools/test/hook/JacocoHook.java
  src/main/java/org/jenkins/tools/test/hook/MinaSshdApi.java
  src/main/java/org/jenkins/tools/test/hook/MultiParentCompileHook.java
  src/main/java/org/jenkins/tools/test/hook/NodeCleanupBeforeCompileHook.java
  src/main/java/org/jenkins/tools/test/hook/PipelineStageViewHook.java
  src/main/java/org/jenkins/tools/test/hook/PluginWithFailsafeIntegrationTestsHook.java
  src/main/java/org/jenkins/tools/test/hook/PluginWithIntegrationTestsHook.java
  src/main/java/org/jenkins/tools/test/hook/SkipUIHelperPlugins.java
  src/main/java/org/jenkins/tools/test/hook/SwarmHook.java
  src/main/java/org/jenkins/tools/test/hook/WarningsNGCheckoutHook.java
  src/main/java/org/jenkins/tools/test/hook/WarningsNGExecutionHook.java
  src/main/java/org/jenkins/tools/test/maven/ExternalMavenRunner.java
  src/main/java/org/jenkins/tools/test/model/MavenCoordinates.java
  src/main/java/org/jenkins/tools/test/model/MavenPom.java
  src/main/java/org/jenkins/tools/test/model/PluginCompatReport.java
  src/main/java/org/jenkins/tools/test/model/PluginCompatResult.java
  src/main/java/org/jenkins/tools/test/model/PluginCompatTesterConfig.java
  src/main/java/org/jenkins/tools/test/model/PluginInfos.java
  src/main/java/org/jenkins/tools/test/model/PluginRemoting.java
  src/main/java/org/jenkins/tools/test/model/PomData.java
  src/main/java/org/jenkins/tools/test/model/TestExecutionResult.java
  src/main/java/org/jenkins/tools/test/model/TestStatus.java
  src/main/java/org/jenkins/tools/test/model/comparators/VersionComparator.java
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHook.java
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHookBeforeCheckout.java
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHookBeforeCompile.java
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHookBeforeExecution.java
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHooks.java
  src/main/java/org/jenkins/tools/test/util/ExecutedTestNamesDetails.java
  src/main/resources/org/jenkins/tools/test/logging/logging.properties
  src/test/java/org/jenkins/tools/test/PluginCompatTesterTest.java
  src/test/java/org/jenkins/tools/test/ScmConnectionSpecialCasesTest.java
  src/test/java/org/jenkins/tools/test/VersionComparatorTest.java
  src/test/java/org/jenkins/tools/test/hook/JacocoHookTest.java
  src/test/java/org/jenkins/tools/test/hook/WarningsNGExecutionHookTest.java
  src/test/java/org/jenkins/tools/test/model/MavenPomTest.java
Labels: internal

#434 Format code with Google Java Format
  pom.xml
  src/main/java/hudson/model/UpdateSite.java
  src/main/java/org/jenkins/tools/test/CliOptions.java
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/PluginCompatTesterCli.java
  src/main/java/org/jenkins/tools/test/exception/ExecutedTestNamesSolverException.java
  src/main/java/org/jenkins/tools/test/exception/PluginSourcesUnavailableException.java
  src/main/java/org/jenkins/tools/test/exception/PomExecutionException.java
  src/main/java/org/jenkins/tools/test/exception/PomTransformationException.java
  src/main/java/org/jenkins/tools/test/hook/AbstractMultiParentHook.java
  src/main/java/org/jenkins/tools/test/hook/BlueOceanHook.java
  src/main/java/org/jenkins/tools/test/hook/DeclarativePipelineHook.java
  src/main/java/org/jenkins/tools/test/hook/DeclarativePipelineMigrationHook.java
  src/main/java/org/jenkins/tools/test/hook/JacocoHook.java
  src/main/java/org/jenkins/tools/test/hook/MultiParentCompileHook.java
  src/main/java/org/jenkins/tools/test/hook/NodeCleanupBeforeCompileHook.java
  src/main/java/org/jenkins/tools/test/hook/PipelineStageViewHook.java
  src/main/java/org/jenkins/tools/test/hook/PluginWithFailsafeIntegrationTestsHook.java
  src/main/java/org/jenkins/tools/test/hook/PluginWithIntegrationTestsHook.java
  src/main/java/org/jenkins/tools/test/hook/SkipUIHelperPlugins.java
  src/main/java/org/jenkins/tools/test/hook/WarningsNGCheckoutHook.java
  src/main/java/org/jenkins/tools/test/hook/WarningsNGExecutionHook.java
  src/main/java/org/jenkins/tools/test/hook/WorkflowCpsHook.java
  src/main/java/org/jenkins/tools/test/logging/LoggingConfiguration.java
  src/main/java/org/jenkins/tools/test/maven/ExternalMavenRunner.java
  src/main/java/org/jenkins/tools/test/maven/MavenRunner.java
  src/main/java/org/jenkins/tools/test/model/MavenCoordinates.java
  src/main/java/org/jenkins/tools/test/model/MavenPom.java
  src/main/java/org/jenkins/tools/test/model/PluginCompatReport.java
  src/main/java/org/jenkins/tools/test/model/PluginCompatResult.java
  src/main/java/org/jenkins/tools/test/model/PluginCompatTesterConfig.java
  src/main/java/org/jenkins/tools/test/model/PluginInfos.java
  src/main/java/org/jenkins/tools/test/model/PluginRemoting.java
  src/main/java/org/jenkins/tools/test/model/PomData.java
  src/main/java/org/jenkins/tools/test/model/TestExecutionResult.java
  src/main/java/org/jenkins/tools/test/model/TestStatus.java
  src/main/java/org/jenkins/tools/test/model/comparators/VersionComparator.java
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHook.java
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHookBeforeCheckout.java
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHookBeforeCompile.java
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHookBeforeExecution.java
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHooks.java
  src/main/java/org/jenkins/tools/test/util/ExecutedTestNamesDetails.java
  src/main/java/org/jenkins/tools/test/util/ExecutedTestNamesSolver.java
  src/main/java/org/jenkins/tools/test/util/StreamGobbler.java
  src/test/java/org/jenkins/tools/test/PluginCompatTesterTest.java
  src/test/java/org/jenkins/tools/test/ScmConnectionSpecialCasesTest.java
  src/test/java/org/jenkins/tools/test/VersionComparatorTest.java
  src/test/java/org/jenkins/tools/test/hook/JacocoHookTest.java
  src/test/java/org/jenkins/tools/test/hook/WarningsNGExecutionHookTest.java
  src/test/java/org/jenkins/tools/test/model/MavenPomTest.java
Labels: internal

#436 Simplify `PluginCompatTester#testPlugins`
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
Labels: internal

#435 Miscellaneous code cleanup
  src/main/java/org/jenkins/tools/test/CliOptions.java
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/PluginCompatTesterCli.java
  src/main/java/org/jenkins/tools/test/hook/AbstractMultiParentHook.java
  src/main/java/org/jenkins/tools/test/hook/SkipUIHelperPlugins.java
  src/main/java/org/jenkins/tools/test/maven/ExternalMavenRunner.java
  src/main/java/org/jenkins/tools/test/model/MavenPom.java
  src/main/java/org/jenkins/tools/test/model/PluginCompatTesterConfig.java
  src/main/java/org/jenkins/tools/test/util/ExecutedTestNamesSolver.java
  src/test/java/org/jenkins/tools/test/PluginCompatTesterTest.java
  src/test/java/org/jenkins/tools/test/hook/WarningsNGExecutionHookTest.java
  src/test/resources/org/jenkins/tools/test/jenkins-bom.xml
  src/test/resources/org/jenkins/tools/test/m2-settings.xml
Labels: internal

#438 Remove `-testJavaArgs`
  README.md
  src/main/docker/run-pct.sh
  src/main/java/org/jenkins/tools/test/CliOptions.java
  src/main/java/org/jenkins/tools/test/PluginCompatTesterCli.java
  src/main/java/org/jenkins/tools/test/model/PluginCompatTesterConfig.java
Labels: removed

#437 Rationalize error handling
  Makefile
  README.md
  pom.xml
  src/main/docker/run-pct.sh
  src/main/java/org/jenkins/tools/test/CliOptions.java
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/PluginCompatTesterCli.java
  src/main/java/org/jenkins/tools/test/exception/ExecutedTestNamesSolverException.java
  src/main/java/org/jenkins/tools/test/exception/PluginCompatibilityTesterException.java
  src/main/java/org/jenkins/tools/test/exception/PluginSourcesUnavailableException.java
  src/main/java/org/jenkins/tools/test/exception/PomExecutionException.java
  src/main/java/org/jenkins/tools/test/exception/PomTransformationException.java
  src/main/java/org/jenkins/tools/test/hook/AbstractMultiParentHook.java
  src/main/java/org/jenkins/tools/test/hook/MultiParentCompileHook.java
  src/main/java/org/jenkins/tools/test/hook/NodeCleanupBeforeCompileHook.java
  src/main/java/org/jenkins/tools/test/hook/SkipUIHelperPlugins.java
  src/main/java/org/jenkins/tools/test/maven/ExternalMavenRunner.java
  src/main/java/org/jenkins/tools/test/maven/MavenRunner.java
  src/main/java/org/jenkins/tools/test/model/PluginCompatReport.java
  src/main/java/org/jenkins/tools/test/model/PluginCompatResult.java
  src/main/java/org/jenkins/tools/test/model/PluginCompatTesterConfig.java
  src/main/java/org/jenkins/tools/test/model/TestExecutionResult.java
  src/main/java/org/jenkins/tools/test/model/TestStatus.java
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHook.java
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHooks.java
  src/main/java/org/jenkins/tools/test/util/ExecutedTestNamesDetails.java
  src/main/java/org/jenkins/tools/test/util/ExecutedTestNamesSolver.java
  src/main/resources/org/jenkins/tools/test/resultToReport.xsl
Labels: internal

#441 Remove `json-lib`
  pom.xml
  src/main/java/hudson/model/UpdateSite.java
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
Labels: removed

#443 Clean up dependencies
  pom.xml
Labels: dependencies, java

#444 Remove `-testJDKHome` argument
  Makefile
  README.md
  src/main/docker/run-pct.sh
  src/main/java/org/jenkins/tools/test/CliOptions.java
  src/main/java/org/jenkins/tools/test/PluginCompatTesterCli.java
  src/main/java/org/jenkins/tools/test/model/PluginCompatTesterConfig.java
Labels: removed

#442 Remove custom XPath logic from `PluginRemoting`
  src/main/java/org/jenkins/tools/test/model/PluginRemoting.java
  src/test/java/org/jenkins/tools/test/ScmConnectionSpecialCasesTest.java
Labels: removed

#446 Remove `SkipUIHelperPlugins`
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/hook/SkipUIHelperPlugins.java
Labels: removed

#445 Remove `-mavenOptions` argument
  src/main/java/org/jenkins/tools/test/CliOptions.java
  src/main/java/org/jenkins/tools/test/PluginCompatTesterCli.java
  src/main/java/org/jenkins/tools/test/maven/ExternalMavenRunner.java
  src/main/java/org/jenkins/tools/test/maven/MavenRunner.java
  src/main/java/org/jenkins/tools/test/model/PluginCompatTesterConfig.java
Labels: removed

#447 Remove unused `Add-Opens` directive
  pom.xml
Labels: removed

#450 allow interpolation of SCM urls
  src/main/java/org/jenkins/tools/test/model/PluginRemoting.java
  src/test/java/org/jenkins/tools/test/model/PluginRemotingTest.java
Labels: internal, enhancement

#451 Parse `pom.xml` without SCM section in `PluginRemoting#retrievePomData`
  src/main/java/org/jenkins/tools/test/model/PluginRemoting.java
  src/test/java/org/jenkins/tools/test/model/PluginRemotingTest.java
  src/test/resources/org/jenkins/tools/test/model/scm/pom.xml
  src/test/resources/org/jenkins/tools/test/model/smokes/pom.xml
Labels: bug

#448 Clean up CLI
  Makefile
  README.md
  pom.xml
  src/main/docker/run-pct.sh
  src/main/java/org/jenkins/tools/test/CliOptions.java
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/PluginCompatTesterCli.java
  src/main/java/org/jenkins/tools/test/hook/AbstractMultiParentHook.java
  src/main/java/org/jenkins/tools/test/hook/MultiParentCompileHook.java
  src/main/java/org/jenkins/tools/test/hook/PluginWithFailsafeIntegrationTestsHook.java
  src/main/java/org/jenkins/tools/test/hook/PluginWithIntegrationTestsHook.java
  src/main/java/org/jenkins/tools/test/maven/ExternalMavenRunner.java
  src/main/java/org/jenkins/tools/test/maven/MavenRunner.java
  src/main/java/org/jenkins/tools/test/model/PluginCompatTesterConfig.java
  src/test/java/org/jenkins/tools/test/hook/JacocoHookTest.java
  src/test/java/org/jenkins/tools/test/hook/WarningsNGExecutionHookTest.java
Labels: breaking

#459 Inline SpotBugs exclusions
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/hook/AbstractMultiParentHook.java
  src/main/java/org/jenkins/tools/test/hook/MultiParentCompileHook.java
  src/main/java/org/jenkins/tools/test/maven/ExternalMavenRunner.java
  src/main/java/org/jenkins/tools/test/model/MavenPom.java
  src/main/java/org/jenkins/tools/test/model/PluginRemoting.java
  src/spotbugs/excludesFilter.xml
Labels: internal

#460 Upgrade to JUnit 5
  pom.xml
  src/test/java/org/jenkins/tools/test/PluginCompatTesterTest.java
  src/test/java/org/jenkins/tools/test/VersionComparatorTest.java
  src/test/java/org/jenkins/tools/test/hook/JacocoHookTest.java
  src/test/java/org/jenkins/tools/test/hook/WarningsNGExecutionHookTest.java
  src/test/java/org/jenkins/tools/test/model/MavenPomTest.java
  src/test/java/org/jenkins/tools/test/model/PluginRemotingTest.java
Labels: test

#453 Remove support for plugins without an SCM tag
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/hook/AbstractMultiParentHook.java
  src/main/java/org/jenkins/tools/test/hook/AwsJavaSdkHook.java
  src/main/java/org/jenkins/tools/test/hook/BlueOceanHook.java
  src/main/java/org/jenkins/tools/test/hook/ConfigurationAsCodeHook.java
  src/main/java/org/jenkins/tools/test/hook/DeclarativePipelineHook.java
  src/main/java/org/jenkins/tools/test/hook/DeclarativePipelineMigrationHook.java
  src/main/java/org/jenkins/tools/test/hook/MinaSshdApi.java
  src/main/java/org/jenkins/tools/test/hook/PipelineStageViewHook.java
  src/main/java/org/jenkins/tools/test/hook/SwarmHook.java
  src/main/java/org/jenkins/tools/test/hook/WarningsNGCheckoutHook.java
  src/main/java/org/jenkins/tools/test/hook/WorkflowCpsHook.java
  src/main/java/org/jenkins/tools/test/model/PluginRemoting.java
  src/main/java/org/jenkins/tools/test/model/PomData.java
  src/test/java/org/jenkins/tools/test/model/PluginRemotingTest.java
  src/test/resources/org/jenkins/tools/test/model/scm/pom.xml
Labels: removed

#462 Fix opt-in for Maven Failsafe plugin
  src/main/java/org/jenkins/tools/test/hook/AnalysisPomExecutionHook.java
  src/main/java/org/jenkins/tools/test/hook/PluginWithFailsafeIntegrationTestsHook.java
Labels: bug

#467 Rename test resource to match test name
  src/test/java/org/jenkins/tools/test/model/PluginRemotingTest.java
  src/test/resources/org/jenkins/tools/test/model/parent/pom.xml
Labels: test

#465 Clean up hooks subsystem
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/hook/AbstractMultiParentHook.java
  src/main/java/org/jenkins/tools/test/hook/AnalysisPomExecutionHook.java
  src/main/java/org/jenkins/tools/test/hook/AwsJavaSdkHook.java
  src/main/java/org/jenkins/tools/test/hook/BlueOceanHook.java
  src/main/java/org/jenkins/tools/test/hook/ConfigurationAsCodeHook.java
  src/main/java/org/jenkins/tools/test/hook/DeclarativePipelineHook.java
  src/main/java/org/jenkins/tools/test/hook/DeclarativePipelineMigrationHook.java
  src/main/java/org/jenkins/tools/test/hook/JacocoHook.java
  src/main/java/org/jenkins/tools/test/hook/MinaSshdApi.java
  src/main/java/org/jenkins/tools/test/hook/MultiParentCompileHook.java
  src/main/java/org/jenkins/tools/test/hook/NodeCleanupBeforeCompileHook.java
  src/main/java/org/jenkins/tools/test/hook/PipelineStageViewHook.java
  src/main/java/org/jenkins/tools/test/hook/PluginWithIntegrationTestsHook.java
  src/main/java/org/jenkins/tools/test/hook/SwarmHook.java
  src/main/java/org/jenkins/tools/test/hook/WarningsNGCheckoutHook.java
  src/main/java/org/jenkins/tools/test/hook/WarningsNGExecutionHook.java
  src/main/java/org/jenkins/tools/test/hook/WorkflowCpsHook.java
  src/main/java/org/jenkins/tools/test/model/PluginInfos.java
  src/main/java/org/jenkins/tools/test/model/hook/BeforeCheckoutContext.java
  src/main/java/org/jenkins/tools/test/model/hook/BeforeCompilationContext.java
  src/main/java/org/jenkins/tools/test/model/hook/BeforeExecutionContext.java
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHook.java
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHookBeforeCheckout.java
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHookBeforeCompile.java
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHookBeforeExecution.java
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHooks.java
  src/main/java/org/jenkins/tools/test/model/hook/Stage.java
  src/main/java/org/jenkins/tools/test/model/hook/StageContext.java
  src/test/java/org/jenkins/tools/test/hook/JacocoHookTest.java
  src/test/java/org/jenkins/tools/test/hook/WarningsNGExecutionHookTest.java
Labels: breaking

#469 Re-introduce test coverage
  pom.xml
  src/test/java/org/jenkins/tools/test/PluginCompatTesterTest.java
Labels: test

#473 Remove Docker subsystem
  .dockerignore
  Dockerfile
  Jenkinsfile
  Makefile
  README.md
  src/main/docker/installWARSnapshots.groovy
  src/main/docker/pct-default-settings.xml
  src/main/docker/readJenkinsVersion.groovy
  src/main/docker/run-pct.sh
Labels: removed

#474 Enable code coverage
  pom.xml
  src/test/java/org/jenkins/tools/test/model/PluginRemotingTest.java
  src/test/resources/org/jenkins/tools/test/model/negative/pom.xml
Labels: test

#475 Improve test coverage
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/test/java/org/jenkins/tools/test/PluginCompatTesterTest.java
Labels: test

#476 Miscellaneous code cleanup
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/hook/MultiParentCompileHook.java
  src/main/java/org/jenkins/tools/test/hook/PluginWithIntegrationTestsHook.java
  src/main/java/org/jenkins/tools/test/model/MavenPom.java
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHooks.java
  src/test/java/org/jenkins/tools/test/model/PluginRemotingTest.java
Labels: internal
