Repository jenkinsci/plugin-compat-tester, pull requests merged in 2023-01, with the labels that each got.

#392 Upgrade most dependencies
  .mvn/extensions.xml
  Dockerfile
  Jenkinsfile
  Makefile
  README.md
  pom.xml
  src/it/war-with-plugins-test/Makefile
  src/it/war-with-plugins-test/README.md
  src/it/war-with-plugins-test/packager-config.yml
  src/it/war-with-plugins-test/pom.xml
  src/main/docker/run-pct.sh
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHooks.java
  src/spotbugs/excludesFilter.xml
Labels: dependencies, java

#401 Remove no-longer-necessary SpotBugs suppressions
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/exception/PomExecutionException.java
  src/main/java/org/jenkins/tools/test/logging/SystemIOLoggerFilter.java
  src/main/java/org/jenkins/tools/test/model/MavenBom.java
  src/main/java/org/jenkins/tools/test/model/PluginCompatTesterConfig.java
  src/main/java/org/jenkins/tools/test/model/PomData.java
  src/main/java/org/jenkins/tools/test/model/TestExecutionResult.java
Labels: internal

#399 Miscellaneous code cleanup
  pom.xml
  src/main/java/org/jenkins/tools/test/CliOptions.java
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/PluginCompatTesterCli.java
  src/main/java/org/jenkins/tools/test/exception/PomExecutionException.java
  src/main/java/org/jenkins/tools/test/hook/AbstractMultiParentHook.java
  src/main/java/org/jenkins/tools/test/hook/ExampleMultiParent.java
  src/main/java/org/jenkins/tools/test/hook/JacocoHook.java
  src/main/java/org/jenkins/tools/test/hook/MultiParentCompileHook.java
  src/main/java/org/jenkins/tools/test/hook/NodeCleanupBeforeCompileHook.java
  src/main/java/org/jenkins/tools/test/hook/NonStandardTagHook.java
  src/main/java/org/jenkins/tools/test/hook/PipelineStageViewHook.java
  src/main/java/org/jenkins/tools/test/hook/PluginWithFailsafeIntegrationTestsHook.java
  src/main/java/org/jenkins/tools/test/hook/PluginWithIntegrationTestsHook.java
  src/main/java/org/jenkins/tools/test/hook/SkipUIHelperPlugins.java
  src/main/java/org/jenkins/tools/test/hook/StructsHook.java
  src/main/java/org/jenkins/tools/test/maven/ExternalMavenRunner.java
  src/main/java/org/jenkins/tools/test/model/MavenBom.java
  src/main/java/org/jenkins/tools/test/model/MavenCoordinates.java
  src/main/java/org/jenkins/tools/test/model/MavenPom.java
  src/main/java/org/jenkins/tools/test/model/PCTPlugin.java
  src/main/java/org/jenkins/tools/test/model/PluginCompatReport.java
  src/main/java/org/jenkins/tools/test/model/PluginCompatResult.java
  src/main/java/org/jenkins/tools/test/model/PluginCompatTesterConfig.java
  src/main/java/org/jenkins/tools/test/model/PluginInfos.java
  src/main/java/org/jenkins/tools/test/model/PluginRemoting.java
  src/main/java/org/jenkins/tools/test/model/PomData.java
  src/main/java/org/jenkins/tools/test/model/TestExecutionResult.java
  src/main/java/org/jenkins/tools/test/model/comparators/MavenCoordinatesComparator.java
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHooks.java
  src/main/java/org/jenkins/tools/test/util/ExecutedTestNamesDetails.java
  src/main/java/org/jenkins/tools/test/util/StreamGobbler.java
  src/test/java/org/jenkins/tools/test/NonStandardTagHookTest.java
  src/test/java/org/jenkins/tools/test/PluginCompatTesterTest.java
  src/test/java/org/jenkins/tools/test/ScmConnectionSpecialCasesTest.java
  src/test/java/org/jenkins/tools/test/VersionComparatorTest.java
  src/test/java/org/jenkins/tools/test/hook/JacocoHookTest.java
  src/test/java/org/jenkins/tools/test/hook/WarningsNGExecutionHookTest.java
  src/test/java/org/jenkins/tools/test/model/MavenPomTest.java
Labels: internal

#400 Rationalize logging subsystem
  logback.xml
  pom.xml
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/PluginCompatTesterCli.java
  src/main/java/org/jenkins/tools/test/hook/AbstractMultiParentHook.java
  src/main/java/org/jenkins/tools/test/hook/ExampleMultiParent.java
  src/main/java/org/jenkins/tools/test/hook/MultiParentCompileHook.java
  src/main/java/org/jenkins/tools/test/hook/NodeCleanupBeforeCompileHook.java
  src/main/java/org/jenkins/tools/test/hook/NonStandardTagHook.java
  src/main/java/org/jenkins/tools/test/hook/TransformPom.java
  src/main/java/org/jenkins/tools/test/hook/WarningsNGCheckoutHook.java
  src/main/java/org/jenkins/tools/test/logging/LoggingConfiguration.java
  src/main/java/org/jenkins/tools/test/maven/ExternalMavenRunner.java
  src/main/java/org/jenkins/tools/test/model/MavenBom.java
  src/main/java/org/jenkins/tools/test/model/MavenPom.java
  src/main/java/org/jenkins/tools/test/model/PluginCompatTesterConfig.java
  src/main/java/org/jenkins/tools/test/model/PluginRemoting.java
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHooks.java
  src/main/resources/org/jenkins/tools/test/logging/logging.properties
  src/test/resources/logback-test.xml
Labels: internal

#403 Clean up hooks
  src/main/java/org/jenkins/tools/test/hook/AbstractMultiParentHook.java
  src/main/java/org/jenkins/tools/test/hook/AwsJavaSdkHook.java
  src/main/java/org/jenkins/tools/test/hook/BlueOceanHook.java
  src/main/java/org/jenkins/tools/test/hook/ConfigurationAsCodeHook.java
  src/main/java/org/jenkins/tools/test/hook/DeclarativePipelineHook.java
  src/main/java/org/jenkins/tools/test/hook/DeclarativePipelineMigrationHook.java
  src/main/java/org/jenkins/tools/test/hook/MinaSshdApi.java
  src/main/java/org/jenkins/tools/test/hook/PipelineStageViewHook.java
  src/main/java/org/jenkins/tools/test/hook/StructsHook.java
  src/main/java/org/jenkins/tools/test/hook/SwarmHook.java
  src/main/java/org/jenkins/tools/test/hook/WorkflowCpsHook.java
Labels: internal

#412 Do not force Windows users to set a Maven installation
  src/main/java/org/jenkins/tools/test/maven/ExternalMavenRunner.java
  src/test/java/org/jenkins/tools/test/PluginCompatTesterTest.java
Labels: bug

#404 Remove usage of Maven SCM API
  pom.xml
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/PluginCompatTesterCli.java
  src/main/java/org/jenkins/tools/test/SCMManagerFactory.java
  src/main/java/org/jenkins/tools/test/hook/AbstractMultiParentHook.java
  src/test/java/org/jenkins/tools/test/NonStandardTagHookTest.java
  src/test/java/org/jenkins/tools/test/PluginCompatTesterTest.java
Labels: internal

#418 Remove `SystemIOLoggerFilter`
  src/main/java/org/jenkins/tools/test/logging/SystemIOLoggerFilter.java
Labels: removed

#417 Remove `src/test/resources/test.log`
  src/test/resources/test.log
Labels: removed

#410 Remove dependency on Jenkins core
  pom.xml
  src/main/java/hudson/model/UpdateSite.java
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/maven/ExternalMavenRunner.java
  src/main/java/org/jenkins/tools/test/model/MavenBom.java
  src/main/java/org/jenkins/tools/test/model/MavenPom.java
  src/main/java/org/jenkins/tools/test/model/PluginCompatReport.java
  src/test/java/org/jenkins/tools/test/NonStandardTagHookTest.java
Labels: removed

#414 Remove 500 lines of dead code
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/hook/TransformPom.java
  src/test/java/org/jenkins/tools/test/PluginCompatTesterTest.java
  src/test/resources/bad-surefire-exclusion-list
Labels: removed

#415 Remove usages of `org.springframework.core.io.ClassPathResource`
  pom.xml
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/resources/org/jenkins/tools/test/resultToReport.xsl
  src/test/java/org/jenkins/tools/test/NonStandardTagHookTest.java
  src/test/java/org/jenkins/tools/test/PluginCompatTesterTest.java
  src/test/resources/org/jenkins/tools/test/jenkins-bom.xml
  src/test/resources/org/jenkins/tools/test/m2-settings.xml
Labels: removed

#416 Remove `NonStandardTagHook`
  README.md
  src/main/java/org/jenkins/tools/test/hook/NonStandardTagHook.java
  src/main/resources/nonstandardtagplugins.properties
  src/test/java/org/jenkins/tools/test/NonStandardTagHookTest.java
  src/test/resources/nonstandardtagplugins.properties
Labels: removed
