Repository jenkinsci/plugin-compat-tester, pull requests merged in 2023-03, with the labels that each got.

#477 Remove Node.js logic
  src/main/java/org/jenkins/tools/test/hook/MultiParentCompileHook.java
  src/main/java/org/jenkins/tools/test/hook/NodeCleanupBeforeCompileHook.java
Labels: removed

#480 use redirect file for help:evaluate
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/hook/MultiParentCompileHook.java
  src/main/java/org/jenkins/tools/test/maven/ExternalMavenRunner.java
Labels: enhancement

#472 Use Maven model directly
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/hook/AbstractMultiParentHook.java
  src/main/java/org/jenkins/tools/test/hook/AnalysisPomExecutionHook.java
  src/main/java/org/jenkins/tools/test/hook/AwsJavaSdkHook.java
  src/main/java/org/jenkins/tools/test/hook/BlueOceanHook.java
  src/main/java/org/jenkins/tools/test/hook/ConfigurationAsCodeHook.java
  src/main/java/org/jenkins/tools/test/hook/DeclarativePipelineHook.java
  src/main/java/org/jenkins/tools/test/hook/DeclarativePipelineMigrationHook.java
  src/main/java/org/jenkins/tools/test/hook/JacocoHook.java
  src/main/java/org/jenkins/tools/test/hook/MinaSshdApi.java
  src/main/java/org/jenkins/tools/test/hook/MultiParentCompileHook.java
  src/main/java/org/jenkins/tools/test/hook/PipelineStageViewHook.java
  src/main/java/org/jenkins/tools/test/hook/SwarmHook.java
  src/main/java/org/jenkins/tools/test/hook/WarningsNGCheckoutHook.java
  src/main/java/org/jenkins/tools/test/hook/WarningsNGExecutionHook.java
  src/main/java/org/jenkins/tools/test/hook/WorkflowCpsHook.java
  src/main/java/org/jenkins/tools/test/model/MavenCoordinates.java
  src/main/java/org/jenkins/tools/test/model/MavenPom.java
  src/main/java/org/jenkins/tools/test/model/PluginRemoting.java
  src/main/java/org/jenkins/tools/test/model/PomData.java
  src/main/java/org/jenkins/tools/test/model/comparators/VersionComparator.java
  src/main/java/org/jenkins/tools/test/model/hook/BeforeCheckoutContext.java
  src/main/java/org/jenkins/tools/test/model/hook/BeforeCompilationContext.java
  src/main/java/org/jenkins/tools/test/model/hook/BeforeExecutionContext.java
  src/main/java/org/jenkins/tools/test/model/hook/StageContext.java
  src/test/java/org/jenkins/tools/test/VersionComparatorTest.java
  src/test/java/org/jenkins/tools/test/hook/JacocoHookTest.java
  src/test/java/org/jenkins/tools/test/hook/WarningsNGExecutionHookTest.java
  src/test/java/org/jenkins/tools/test/model/MavenPomTest.java
  src/test/java/org/jenkins/tools/test/model/PluginRemotingTest.java
Labels: breaking

#481 Get rid of Reflections in `PluginCompatTesterHooks`
  pom.xml
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/PluginCompatTesterCli.java
  src/main/java/org/jenkins/tools/test/hook/AnalysisPomExecutionHook.java
  src/main/java/org/jenkins/tools/test/hook/AwsJavaSdkHook.java
  src/main/java/org/jenkins/tools/test/hook/BlueOceanHook.java
  src/main/java/org/jenkins/tools/test/hook/ConfigurationAsCodeHook.java
  src/main/java/org/jenkins/tools/test/hook/DeclarativePipelineHook.java
  src/main/java/org/jenkins/tools/test/hook/DeclarativePipelineMigrationHook.java
  src/main/java/org/jenkins/tools/test/hook/HpiPluginHook.java
  src/main/java/org/jenkins/tools/test/hook/JacocoHook.java
  src/main/java/org/jenkins/tools/test/hook/MinaSshdApi.java
  src/main/java/org/jenkins/tools/test/hook/MultiParentCompileHook.java
  src/main/java/org/jenkins/tools/test/hook/PipelineStageViewHook.java
  src/main/java/org/jenkins/tools/test/hook/SwarmHook.java
  src/main/java/org/jenkins/tools/test/hook/WarningsNGCheckoutHook.java
  src/main/java/org/jenkins/tools/test/hook/WarningsNGExecutionHook.java
  src/main/java/org/jenkins/tools/test/hook/WorkflowCpsHook.java
  src/main/java/org/jenkins/tools/test/model/PluginCompatTesterConfig.java
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHooks.java
  src/main/resources/org/jenkins/tools/test/logging/logging.properties
Labels: breaking

#482 Remove ESLint logic
  src/main/java/org/jenkins/tools/test/hook/MultiParentCompileHook.java
Labels: removed

#483 validate file based arguments point to existing files / directories
  .mvn/jvm.config
  pom.xml
  src/main/java/org/jenkins/tools/test/PluginCompatTesterCli.java
  src/main/java/org/jenkins/tools/test/picocli/ExistingFileTypeConverter.java
  src/test/java/org/jenkins/tools/test/picocli/ExistingFileTypeConverterTest.java
Labels: enhancement

#486 Improve consistency of hooks
  src/main/java/org/jenkins/tools/test/hook/HpiPluginHook.java
  src/main/java/org/jenkins/tools/test/hook/JacocoHook.java
  src/main/java/org/jenkins/tools/test/hook/WarningsNGCheckoutHook.java
  src/main/java/org/jenkins/tools/test/hook/WarningsNGExecutionHook.java
  src/main/java/org/jenkins/tools/test/hook/WorkflowCpsHook.java
  src/test/java/org/jenkins/tools/test/hook/JacocoHookTest.java
  src/test/java/org/jenkins/tools/test/hook/WarningsNGExecutionHookTest.java
Labels: internal

#491 JaCoCo hook no longer runs
  src/main/java/org/jenkins/tools/test/hook/JacocoHook.java
Labels: bug

#498 Allow Dependabot to update Jenkins core
  pom.xml
Labels: bug

#502 Do not log `null` build log file
  src/main/java/org/jenkins/tools/test/maven/ExternalMavenRunner.java
Labels: bug

#501 Move `UpdateSite` into PCT package
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/model/UpdateSite.java
  src/main/java/org/jenkins/tools/test/model/hook/BeforeCheckoutContext.java
  src/main/java/org/jenkins/tools/test/model/hook/BeforeCompilationContext.java
  src/main/java/org/jenkins/tools/test/model/hook/BeforeExecutionContext.java
  src/main/java/org/jenkins/tools/test/model/hook/StageContext.java
  src/test/java/org/jenkins/tools/test/PluginCompatTesterTest.java
Labels: breaking

#499 Fail fast when attempting to run PCT against a release with a missing or nondeterministic tag
  src/main/java/org/jenkins/tools/test/hook/TagValidationHook.java
Labels: bug

#504 Extract common functionality into property version hook
  src/main/java/org/jenkins/tools/test/hook/HpiPluginHook.java
  src/main/java/org/jenkins/tools/test/hook/PropertyVersionHook.java
Labels: internal

#485 Drop support for `git://` URLs
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
Labels: breaking

#505 Adapt to jenkinsci/maven-hpi-plugin#461
  src/main/java/org/jenkins/tools/test/hook/HpiPluginHook.java
Labels: dependencies, java
