Repository jenkinsci/plugin-compat-tester, pull requests merged in 2023-04, with the labels that each got.

#506 Switch to Palantir Java Format
  pom.xml
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/PluginCompatTesterCli.java
  src/main/java/org/jenkins/tools/test/hook/AbstractMultiParentHook.java
  src/main/java/org/jenkins/tools/test/hook/AnalysisPomExecutionHook.java
  src/main/java/org/jenkins/tools/test/hook/DeclarativePipelineHook.java
  src/main/java/org/jenkins/tools/test/hook/DeclarativePipelineMigrationHook.java
  src/main/java/org/jenkins/tools/test/hook/JacocoHook.java
  src/main/java/org/jenkins/tools/test/hook/MultiParentCompileHook.java
  src/main/java/org/jenkins/tools/test/hook/PipelineStageViewHook.java
  src/main/java/org/jenkins/tools/test/hook/PluginWithFailsafeIntegrationTestsHook.java
  src/main/java/org/jenkins/tools/test/hook/PropertyVersionHook.java
  src/main/java/org/jenkins/tools/test/hook/TagValidationHook.java
  src/main/java/org/jenkins/tools/test/hook/WarningsNGCheckoutHook.java
  src/main/java/org/jenkins/tools/test/logging/LoggingConfiguration.java
  src/main/java/org/jenkins/tools/test/maven/ExternalMavenRunner.java
  src/main/java/org/jenkins/tools/test/model/MavenPom.java
  src/main/java/org/jenkins/tools/test/model/PluginCompatTesterConfig.java
  src/main/java/org/jenkins/tools/test/model/PluginRemoting.java
  src/main/java/org/jenkins/tools/test/model/UpdateSite.java
  src/main/java/org/jenkins/tools/test/model/hook/BeforeCheckoutContext.java
  src/main/java/org/jenkins/tools/test/model/hook/BeforeCompilationContext.java
  src/main/java/org/jenkins/tools/test/model/hook/BeforeExecutionContext.java
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHookBeforeCheckout.java
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHookBeforeCompile.java
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHookBeforeExecution.java
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHooks.java
  src/main/java/org/jenkins/tools/test/model/hook/StageContext.java
  src/main/java/org/jenkins/tools/test/util/StreamGobbler.java
  src/test/java/org/jenkins/tools/test/PluginCompatTesterTest.java
  src/test/java/org/jenkins/tools/test/hook/JacocoHookTest.java
  src/test/java/org/jenkins/tools/test/hook/WarningsNGExecutionHookTest.java
  src/test/java/org/jenkins/tools/test/model/MavenPomTest.java
  src/test/java/org/jenkins/tools/test/model/PluginRemotingTest.java
  src/test/java/org/jenkins/tools/test/picocli/ExistingFileTypeConverterTest.java
Labels: internal

#507 Update `.git-blame-ignore-revs`
  .git-blame-ignore-revs
Labels: skip-changelog

#516 Add `serialVersionUID` to exception classes
  src/main/java/org/jenkins/tools/test/exception/PluginCompatibilityTesterException.java
  src/main/java/org/jenkins/tools/test/exception/PluginSourcesUnavailableException.java
  src/main/java/org/jenkins/tools/test/exception/PomExecutionException.java
  src/main/java/org/jenkins/tools/test/exception/PomTransformationException.java
Labels: skip-changelog

#517 Add version provider
  pom.xml
  src/main/java/org/jenkins/tools/test/PluginCompatTesterCli.java
  src/main/java/org/jenkins/tools/test/VersionProvider.java
Labels: enhancement

#518 Use list rather than set in CLI
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/PluginCompatTesterCli.java
  src/main/java/org/jenkins/tools/test/model/PluginCompatTesterConfig.java
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHooks.java
  src/main/java/org/jenkins/tools/test/picocli/ExistingFileTypeConverter.java
Labels: internal

#519 Simplify core coördinates
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/hook/MultiParentCompileHook.java
  src/main/java/org/jenkins/tools/test/model/hook/BeforeCheckoutContext.java
  src/main/java/org/jenkins/tools/test/model/hook/BeforeCompilationContext.java
  src/main/java/org/jenkins/tools/test/model/hook/BeforeExecutionContext.java
  src/main/java/org/jenkins/tools/test/model/hook/StageContext.java
Labels: breaking

#520 Remove `transformPom`
  src/main/java/org/jenkins/tools/test/model/MavenPom.java
  src/test/java/org/jenkins/tools/test/model/MavenPomTest.java
  src/test/resources/org/jenkins/tools/test/model/demo-plugin-pom-after.xml
  src/test/resources/org/jenkins/tools/test/model/demo-plugin-pom-before.xml
Labels: removed

#521 Introduce a `HookOrder` annotation to order hooks
  src/main/java/org/jenkins/tools/test/model/hook/HookOrder.java
  src/main/java/org/jenkins/tools/test/model/hook/HookOrderComparator.java
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHooks.java
  src/test/java/org/jenkins/tools/test/model/hook/HookOrderComparatorTest.java
Labels: enhancement

#522 Refactor expression evaluation
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/hook/MultiParentCompileHook.java
  src/main/java/org/jenkins/tools/test/hook/PropertyVersionHook.java
  src/main/java/org/jenkins/tools/test/maven/ExpressionEvaluator.java
Labels: enhancement

#523 Miscellaneous cleanup
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/VersionProvider.java
  src/main/java/org/jenkins/tools/test/model/PluginCompatTesterConfig.java
Labels: skip-changelog

#524 Move the logic of chaining or throwing an exception to a method
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
Labels: chore

#525 We only clone from Git, so strip `scm:git` early
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
Labels: chore

#510 Native support for multi-module Maven projects
  pom.xml
  src/main/java/org/jenkins/tools/test/CLI.java
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/PluginCompatTesterCli.java
  src/main/java/org/jenkins/tools/test/PluginListerCli.java
  src/main/java/org/jenkins/tools/test/exception/MetadataExtractionException.java
  src/main/java/org/jenkins/tools/test/hook/AbstractMultiParentHook.java
  src/main/java/org/jenkins/tools/test/hook/AnalysisPomExecutionHook.java
  src/main/java/org/jenkins/tools/test/hook/AwsJavaSdkHook.java
  src/main/java/org/jenkins/tools/test/hook/BlueOceanHook.java
  src/main/java/org/jenkins/tools/test/hook/ConfigurationAsCodeHook.java
  src/main/java/org/jenkins/tools/test/hook/DeclarativePipelineHook.java
  src/main/java/org/jenkins/tools/test/hook/DeclarativePipelineMigrationHook.java
  src/main/java/org/jenkins/tools/test/hook/JacocoHook.java
  src/main/java/org/jenkins/tools/test/hook/MinaSshdApi.java
  src/main/java/org/jenkins/tools/test/hook/MultiParentCompileHook.java
  src/main/java/org/jenkins/tools/test/hook/PipelineStageViewHook.java
  src/main/java/org/jenkins/tools/test/hook/PropertyVersionHook.java
  src/main/java/org/jenkins/tools/test/hook/SwarmHook.java
  src/main/java/org/jenkins/tools/test/hook/TagValidationHook.java
  src/main/java/org/jenkins/tools/test/hook/WarningsNGCheckoutHook.java
  src/main/java/org/jenkins/tools/test/hook/WarningsNGExecutionHook.java
  src/main/java/org/jenkins/tools/test/hook/WorkflowCpsHook.java
  src/main/java/org/jenkins/tools/test/maven/ExpressionEvaluator.java
  src/main/java/org/jenkins/tools/test/maven/ExternalMavenRunner.java
  src/main/java/org/jenkins/tools/test/maven/MavenRunner.java
  src/main/java/org/jenkins/tools/test/model/PluginRemoting.java
  src/main/java/org/jenkins/tools/test/model/UpdateSite.java
  src/main/java/org/jenkins/tools/test/model/hook/BeforeCheckoutContext.java
  src/main/java/org/jenkins/tools/test/model/hook/BeforeCompilationContext.java
  src/main/java/org/jenkins/tools/test/model/hook/BeforeExecutionContext.java
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHooks.java
  src/main/java/org/jenkins/tools/test/model/hook/StageContext.java
  src/main/java/org/jenkins/tools/test/model/plugin_metadata/LegacyMultiModulePluginMetadataExtractor.java
  src/main/java/org/jenkins/tools/test/model/plugin_metadata/LegacyPluginMetadataExtractor.java
  src/main/java/org/jenkins/tools/test/model/plugin_metadata/LocalCheckoutPluginMetadataExtractor.java
  src/main/java/org/jenkins/tools/test/model/plugin_metadata/ModernPluginMetadataExtractor.java
  src/main/java/org/jenkins/tools/test/model/plugin_metadata/Plugin.java
  src/main/java/org/jenkins/tools/test/model/plugin_metadata/PluginMetadataExtractor.java
  src/main/java/org/jenkins/tools/test/util/ModelReader.java
  src/main/java/org/jenkins/tools/test/util/ServiceHelper.java
  src/main/java/org/jenkins/tools/test/util/WarExtractor.java
  src/test/java/org/jenkins/tools/test/PluginCompatTesterTest.java
  src/test/java/org/jenkins/tools/test/PluginListerCliTest.java
  src/test/java/org/jenkins/tools/test/hook/JacocoHookTest.java
  src/test/java/org/jenkins/tools/test/hook/WarningsNGExecutionHookTest.java
  src/test/java/org/jenkins/tools/test/model/PluginRemotingTest.java
  src/test/java/org/jenkins/tools/test/model/plugin_metadata/ModernPluginMetadataExtractorTest.java
  src/test/java/org/jenkins/tools/test/util/ServiceHelperTest.java
  src/test/java/org/jenkins/tools/test/util/WarExtractorTest.java
  src/test/resources/org/jenkins/tools/test/model/plugin_metadata/ModernPluginMetadataExtractorTest/.gitattributes
  src/test/resources/org/jenkins/tools/test/model/plugin_metadata/ModernPluginMetadataExtractorTest/legacy/MANIFEST.MF
  src/test/resources/org/jenkins/tools/test/model/plugin_metadata/ModernPluginMetadataExtractorTest/modern/MANIFEST.MF
Labels: enhancement, squash-merge-me

#527 Use `Implementation-Build` rather than `Plugin-GitHash`
  src/main/java/org/jenkins/tools/test/model/plugin_metadata/ModernPluginMetadataExtractor.java
  src/test/resources/org/jenkins/tools/test/model/plugin_metadata/ModernPluginMetadataExtractorTest/modern/MANIFEST.MF
Labels: internal

#529 Testing local or embedded plugins is exclusive
  src/main/java/org/jenkins/tools/test/PluginCompatTester.java
  src/main/java/org/jenkins/tools/test/PluginCompatTesterCli.java
  src/main/java/org/jenkins/tools/test/PluginListerCli.java
  src/main/java/org/jenkins/tools/test/util/WarExtractor.java
  src/test/java/org/jenkins/tools/test/util/WarExtractorTest.java
Labels: bug

#535 Add the plugin name to the hook log
  src/main/java/org/jenkins/tools/test/model/hook/PluginCompatTesterHooks.java
Labels: enhancement

#536 Restore repository name to machine-parsable `list-plugins` output
  src/main/java/org/jenkins/tools/test/PluginListerCli.java
  src/test/java/org/jenkins/tools/test/PluginListerCliTest.java
Labels: breaking

#537 Fixup to #536
  src/main/java/org/jenkins/tools/test/PluginListerCli.java
Labels: bug
